---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - lifecycle.edge.suse.com
  resources:
  - edgeupgradeplans
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lifecycle.edge.suse.com
  resources:
  - edgeupgradeplans/finalizers
  verbs:
  - update
- apiGroups:
  - lifecycle.edge.suse.com
  resources:
  - edgeupgradeplans/status
  verbs:
  - get
  - patch
  - update
